/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ─── Stitch ThreatLens design tokens ───
        "surface":                 "#f8f9ff",
        "surface-dim":             "#cbdbf5",
        "surface-bright":          "#f8f9ff",
        "surface-container-lowest":"#ffffff",
        "surface-container-low":   "#eff4ff",
        "surface-container":       "#e5eeff",
        "surface-container-high":  "#dce9ff",
        "surface-container-highest":"#d3e4fe",
        "on-surface":              "#0b1c30",
        "on-surface-variant":      "#45464d",
        "inverse-surface":         "#213145",
        "inverse-on-surface":      "#eaf1ff",
        "outline":                 "#76777d",
        "outline-variant":         "#c6c6cd",
        "surface-tint":            "#565e74",
        // Primary (slate/dark navy)
        "primary":                 "#000000",
        "on-primary":              "#ffffff",
        "primary-container":       "#131b2e",
        "on-primary-container":    "#7c839b",
        "inverse-primary":         "#bec6e0",
        "primary-fixed":           "#dae2fd",
        "primary-fixed-dim":       "#bec6e0",
        "on-primary-fixed":        "#131b2e",
        "on-primary-fixed-variant":"#3f465c",
        // Secondary (electric cobalt blue)
        "secondary":               "#0051d5",
        "on-secondary":            "#ffffff",
        "secondary-container":     "#316bf3",
        "on-secondary-container":  "#fefcff",
        "secondary-fixed":         "#dbe1ff",
        "secondary-fixed-dim":     "#b4c5ff",
        "on-secondary-fixed":      "#00174b",
        "on-secondary-fixed-variant":"#003ea8",
        // Tertiary (tactical crimson)
        "tertiary":                "#000000",
        "on-tertiary":             "#ffffff",
        "tertiary-container":      "#410002",
        "on-tertiary-container":   "#f63a35",
        "tertiary-fixed":          "#ffdad6",
        "tertiary-fixed-dim":      "#ffb4ab",
        "on-tertiary-fixed":       "#410002",
        "on-tertiary-fixed-variant":"#93000b",
        // Error
        "error":                   "#ba1a1a",
        "on-error":                "#ffffff",
        "error-container":         "#ffdad6",
        "on-error-container":      "#93000a",
        // Background
        "background":              "#f8f9ff",
        "on-background":           "#0b1c30",
        "surface-variant":         "#d3e4fe",

        // ─── legacy aliases kept for backward compat ───
        "text-primary":   "#0b1c30",
        "text-secondary": "#45464d",
        "text-muted":     "#76777d",
        "border":         "#c6c6cd",
        "primary-subtle": "#dae2fd",
        "primary-hover":  "#131b2e",
        "background-subtle": "#eff4ff",
      },
      fontFamily: {
        sans:       ["Inter", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono:       ["JetBrains Mono", "SFMono-Regular", "Menlo", "monospace"],
        "data-mono":["JetBrains Mono", "monospace"],
        "label-caps":["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "data-mono":    ["0.75rem",    { lineHeight: "1.125rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "data-mono-sm": ["0.6875rem",  { lineHeight: "1rem",     letterSpacing: "0",       fontWeight: "400" }],
        "label-caps":   ["0.6875rem",  { lineHeight: "1rem",     letterSpacing: "0.08em",  fontWeight: "600" }],
        "headline-sm":  ["1rem",       { lineHeight: "1.5rem",   letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md":  ["1.25rem",    { lineHeight: "1.75rem",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg":  ["1.75rem",    { lineHeight: "2.25rem",  letterSpacing: "-0.025em",fontWeight: "700" }],
        "metric-lg":    ["1.5rem",     { lineHeight: "1.75rem",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "metric-xl":    ["2rem",       { lineHeight: "2.25rem",  letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-sm":      ["0.8125rem",  { lineHeight: "1.25rem",  letterSpacing: "0",       fontWeight: "400" }],
        "body-md":      ["0.875rem",   { lineHeight: "1.375rem", letterSpacing: "0",       fontWeight: "400" }],
        "display":      ["2.25rem",    { lineHeight: "2.75rem",  letterSpacing: "-0.03em", fontWeight: "700" }],
      },
      spacing: {
        "space-xs":  "0.25rem",
        "space-sm":  "0.5rem",
        "space-md":  "0.75rem",
        "space-lg":  "1rem",
        "space-xl":  "1.5rem",
        "space-2xl": "2rem",
        "gutter":    "1rem",
        "gutter-lg": "1.5rem",
        "margin":    "1.5rem",
        "margin-mobile": "1rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:  "0.125rem",
        md:  "0.25rem",
        lg:  "0.375rem",
        xl:  "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        sm:          "0 1px 2px 0 rgba(15,23,42,0.04)",
        card:        "0 1px 3px 0 rgba(15,23,42,0.05), 0 1px 2px -1px rgba(15,23,42,0.05)",
        "card-hover":"0 4px 6px -1px rgba(15,23,42,0.08), 0 2px 4px -2px rgba(15,23,42,0.05)",
        dropdown:    "0 10px 15px -3px rgba(15,23,42,0.08), 0 4px 6px -4px rgba(15,23,42,0.04)",
        button:      "0 1px 2px 0 rgba(37,99,235,0.2)",
        "xs":        "0 1px 2px 0 rgba(15,23,42,0.06)",
      },
    },
  },
  plugins: [],
}
